### ISSUE TITLE
Add an option to disable JavaScript for a capture

### ISSUE THREAD

**Issue by Terrtia** [ail-project/lacus#30]
https://stackoverflow.com/questions/65958243/disable-javascript-in-playwright

**Comment by Rafiot** [comment]
The reference for python: 

https://playwright.dev/python/docs/emulation#javascript-enabled

**Comment by Rafiot** [comment]
Implemented in PlaywrightCapture: https://github.com/Lookyloo/PlaywrightCapture/releases/tag/v1.26.1
