### ISSUE TITLE
Issue with Lacus Crawler

### ISSUE THREAD

**Issue by Pranav-2301** [ail-project/lacus#40]
Hello team,

hope you are doing great. I just installed the new version of AIL and Lacus, and I am now facing some issue with it. 

omething went poorly http://eswpccgr5xyovsahffkehgleqthrasfpfdblwbs4lstd345dwq5qumqd.onion - Capture.__aenter__: 

║ Host system is missing dependencies to run browsers. ║
║ Missing libraries :

Here is the screenshot for the error :

![image](https://github.com/user-attachments/assets/128b5299-3826-48da-acee-5120c19b4b28)

Do you think I should reinstall the crawler or there is another way to do it ?

Looking forward for your support.

**Comment by Rafiot** [comment]
Woops, sorry, that seems to be missing in the documentation, you need to you run the following command from the lacus directory:

`poetry run playwright install-deps`
